package beans;
// Generated 8 sept. 2013 14:58:50 by Hibernate Tools 3.2.1.GA



/**
 * Application generated by hbm2java
 */
public class Application  implements java.io.Serializable {


     private int idApp;
     private Queue queue;
     private String filePath;
     private int maxTime;

    public Application() {
    }

    public Application(int idApp, Queue queue, String filePath, int maxTime) {
       this.idApp = idApp;
       this.queue = queue;
       this.filePath = filePath;
       this.maxTime = maxTime;
    }
   
    public int getIdApp() {
        return this.idApp;
    }
    
    public void setIdApp(int idApp) {
        this.idApp = idApp;
    }
    public Queue getQueue() {
        return this.queue;
    }
    
    public void setQueue(Queue queue) {
        this.queue = queue;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    public int getMaxTime() {
        return this.maxTime;
    }
    
    public void setMaxTime(int maxTime) {
        this.maxTime = maxTime;
    }




}


