package beans;
// Generated 8 sept. 2013 14:58:50 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Job generated by hbm2java
 */
public class Job  implements java.io.Serializable {


     private int idJob;
     private String filePath;
     private String userLogin;
     private String sessionId;
     private String application;
     private String applicationModule;
     private Integer otherClassment;
     private String jobQueue;
     private String position;
     private String state;
     private Date date;
     private Set jobParameters = new HashSet(0);

    public Job() {
    }

	
    public Job(int idJob, String filePath, String jobQueue) {
        this.idJob = idJob;
        this.filePath = filePath;
        this.jobQueue = jobQueue;
    }
    public Job(int idJob, String filePath, String userLogin, String sessionId, String application, String applicationModule, Integer otherClassment, String jobQueue, String position, String state, Date date, Set jobParameters) {
       this.idJob = idJob;
       this.filePath = filePath;
       this.userLogin = userLogin;
       this.sessionId = sessionId;
       this.application = application;
       this.applicationModule = applicationModule;
       this.otherClassment = otherClassment;
       this.jobQueue = jobQueue;
       this.position = position;
       this.state = state;
       this.date = date;
       this.jobParameters = jobParameters;
    }
   
    public int getIdJob() {
        return this.idJob;
    }
    
    public void setIdJob(int idJob) {
        this.idJob = idJob;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    public String getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    public String getApplication() {
        return this.application;
    }
    
    public void setApplication(String application) {
        this.application = application;
    }
    public String getApplicationModule() {
        return this.applicationModule;
    }
    
    public void setApplicationModule(String applicationModule) {
        this.applicationModule = applicationModule;
    }
    public Integer getOtherClassment() {
        return this.otherClassment;
    }
    
    public void setOtherClassment(Integer otherClassment) {
        this.otherClassment = otherClassment;
    }
    public String getJobQueue() {
        return this.jobQueue;
    }
    
    public void setJobQueue(String jobQueue) {
        this.jobQueue = jobQueue;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getJobParameters() {
        return this.jobParameters;
    }
    
    public void setJobParameters(Set jobParameters) {
        this.jobParameters = jobParameters;
    }




}


