package beans;
// Generated 8 sept. 2013 14:58:50 by Hibernate Tools 3.2.1.GA



/**
 * JobParameter generated by hbm2java
 */
public class JobParameter  implements java.io.Serializable {


     private int idJp;
     private Job job;
     private String key;
     private String value;

    public JobParameter() {
    }

    public JobParameter(int idJp, Job job, String key, String value) {
       this.idJp = idJp;
       this.job = job;
       this.key = key;
       this.value = value;
    }
   
    public int getIdJp() {
        return this.idJp;
    }
    
    public void setIdJp(int idJp) {
        this.idJp = idJp;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


