package beans;
// Generated 8 sept. 2013 14:58:50 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Queue generated by hbm2java
 */
public class Queue  implements java.io.Serializable {


     private int idQueue;
     private String nameQueue;
     private String description;
     private int maxTimeIn;
     private int maxRunTime;
     private Set applications = new HashSet(0);

    public Queue() {
    }

	
    public Queue(int idQueue, String nameQueue, String description, int maxTimeIn, int maxRunTime) {
        this.idQueue = idQueue;
        this.nameQueue = nameQueue;
        this.description = description;
        this.maxTimeIn = maxTimeIn;
        this.maxRunTime = maxRunTime;
    }
    public Queue(int idQueue, String nameQueue, String description, int maxTimeIn, int maxRunTime, Set applications) {
       this.idQueue = idQueue;
       this.nameQueue = nameQueue;
       this.description = description;
       this.maxTimeIn = maxTimeIn;
       this.maxRunTime = maxRunTime;
       this.applications = applications;
    }
   
    public int getIdQueue() {
        return this.idQueue;
    }
    
    public void setIdQueue(int idQueue) {
        this.idQueue = idQueue;
    }
    public String getNameQueue() {
        return this.nameQueue;
    }
    
    public void setNameQueue(String nameQueue) {
        this.nameQueue = nameQueue;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getMaxTimeIn() {
        return this.maxTimeIn;
    }
    
    public void setMaxTimeIn(int maxTimeIn) {
        this.maxTimeIn = maxTimeIn;
    }
    public int getMaxRunTime() {
        return this.maxRunTime;
    }
    
    public void setMaxRunTime(int maxRunTime) {
        this.maxRunTime = maxRunTime;
    }
    public Set getApplications() {
        return this.applications;
    }
    
    public void setApplications(Set applications) {
        this.applications = applications;
    }




}


