version: "3.6"
services:
    jre:
        build:
            context: ./java
            dockerfile: DockerFile.jre
            labels:
                com.enioka.description: "build helper - OpenJDK JRE for windows nano"
            args:
                - OJDK_URL=https://github.com/ojdkbuild/ojdkbuild/releases/download/java-1.8.0-openjdk-1.8.0.275-1.b01/java-1.8.0-openjdk-1.8.0.275-1.b01.ojdkbuild.windows.x86_64.zip
                - OJDK_SHA256=efc67ebadaabca65ac89e60697be833b9ff71d6f7df5e3d1b354f2458d76b6d7
                - WINDOWS_TAG=${WINDOWS_TAG}
        image: buildhelpers:jre-1.8.0-${WINDOWS_TAG:?tag must be given}
        hostname: jre
        isolation: hyperv

    jdk:
        build:
            context: ./java
            dockerfile: DockerFile.jdk
            labels:
                com.enioka.description: "build helper - OpenJDK JDK for windows nano"
            args:
                - OJDK_URL=https://github.com/ojdkbuild/ojdkbuild/releases/download/java-1.8.0-openjdk-1.8.0.275-1.b01/java-1.8.0-openjdk-1.8.0.275-1.b01.ojdkbuild.windows.x86_64.zip
                - OJDK_SHA256=efc67ebadaabca65ac89e60697be833b9ff71d6f7df5e3d1b354f2458d76b6d7
                - WINDOWS_TAG=${WINDOWS_TAG}
        image: buildhelpers:jdk-1.8.0-${WINDOWS_TAG:?tag must be given}
        hostname: jdk
        isolation: hyperv

    mvn:
        build:
            context: ./maven
            dockerfile: DockerFile
            labels:
                com.enioka.description: "build helper - Maven build for windows nano"
            args:
                - WINDOWS_TAG=${WINDOWS_TAG}
                - MVN_VERSION=3.5.4
                - MVN_MD5=235db716537989e9e949e5bf23f965c0
        image: buildhelpers:maven-3-${WINDOWS_TAG:?tag must be given}
        hostname: maven
        isolation: hyperv

    jqm:
        build:
            context: ../../
            dockerfile: ./docker/windows/jqm/Dockerfile
            labels:
                com.enioka.description: "official JQM Docker distribution"
            args:
                - WINDOWS_TAG=${WINDOWS_TAG}
        image: ${JQM_IMAGE_NAME}
        isolation: hyperv
