ARG WINDOWS_TAG=1709



###############################################################################
## Build inside full JDK image.
###############################################################################
FROM jqm/maven:latest AS builder

COPY ./jqm-all .

ENV SKIP_TESTS=true

RUN mvn install -DskipTests
RUN IF /I NOT "%SKIP_TESTS%" == "true" (mvn test) ELSE (echo "Skipping tests")



###############################################################################
## Powershell so as to unzip
###############################################################################
FROM microsoft/powershell:nanoserver AS installer

SHELL ["pwsh.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

COPY --from=builder c:\\jqm-service\\target\\jqm-2.1.0-SNAPSHOT.zip .

RUN Expand-Archive jqm*.zip -DestinationPath C:/; \
    rm *.zip; \
	mv jqm* c:/jqm


	
###############################################################################
## Actual image, based on minimal JRE.
###############################################################################
FROM jqm/openjdk:latest-jre

COPY --from=installer C:/jqm/ C:/jqm/
COPY ./docker/windows/selfConfig.xml C:/jqm/selfConfig.xml

ENV JAVA_OPTS "-Xms128m -Xmx512m -XX:MaxMetaspaceSize=128m"
RUN setx PATH %PATH%;C:\\jqm

EXPOSE 1789 1790 1791

WORKDIR jqm

RUN java -jar jqm.jar -u && java -jar jqm.jar -c selfConfig.xml && java -jar jqm.jar -importjobdef ./jobs/jqm-demo/xml/xml-jd-demo.xml && DEL /Q .\\logs\\*

ENTRYPOINT java %JAVA_OPTS% -jar jqm.jar -startnode ContainerNode