version: "3.6"
services:
    jre:
        build:
            context: ./java
            dockerfile: DockerFile.jre
            labels:
                com.enioka.description: "build helper - OpenJDK JRE for windows nano"
            args:
                - OJDK_URL=https://github.com/ojdkbuild/ojdkbuild/releases/download/java-1.8.0-openjdk-1.8.0.322-1.b06/java-1.8.0-openjdk-jre-1.8.0.322-1.b06.ojdkbuild.windows.x86_64.zip
                - OJDK_SHA256=a8527a5320e2638f1c706cb8a7cbfd51b1d5dbb41d34ec8745f680b986e9bd4d
                - WINDOWS_TAG=${WINDOWS_TAG}
        image: buildhelpers:jre-1.8.0-${WINDOWS_TAG:?tag must be given}
        hostname: jre
        isolation: hyperv

    jdk:
        build:
            context: ./java
            dockerfile: DockerFile.jdk
            labels:
                com.enioka.description: "build helper - OpenJDK JDK for windows nano"
            args:
                - OJDK_URL=https://github.com/ojdkbuild/ojdkbuild/releases/download/java-1.8.0-openjdk-1.8.0.322-1.b06/java-1.8.0-openjdk-1.8.0.322-1.b06.ojdkbuild.windows.x86_64.zip
                - OJDK_SHA256=154e7ec1a86025d9f41eef67ae154536d98919fb419f638e4db16f60d2b245ad
                - WINDOWS_TAG=${WINDOWS_TAG}
        image: buildhelpers:jdk-1.8.0-${WINDOWS_TAG:?tag must be given}
        hostname: jdk
        isolation: hyperv

    mvn:
        build:
            context: ./maven
            dockerfile: DockerFile
            labels:
                com.enioka.description: "build helper - Maven build for windows nano"
            args:
                - WINDOWS_TAG=${WINDOWS_TAG}
                - MVN_VERSION=3.8.4
                - MVN_MD5=bcd1e99548ac8a5b9ec159ee16c23d29d6799696c92140d583d25eb323433aadcc0b47c45b0b6bd9dbcf344bbba38b56dd056a9c49ae714cfc22dc06bb4a4230
        image: buildhelpers:maven-3-${WINDOWS_TAG:?tag must be given}
        hostname: maven
        isolation: hyperv

    jqm:
        build:
            context: ../../
            dockerfile: ./docker/windows/jqm/Dockerfile
            labels:
                com.enioka.description: "official JQM Docker distribution"
            args:
                - WINDOWS_TAG=${WINDOWS_TAG}
        image: ${JQM_IMAGE_NAME}
        isolation: hyperv
