version: "3.6"
services:
    jdk:
        build:
            context: ./java
            dockerfile: DockerFile.jdk
            labels:
                com.enioka.description: "build helper - OpenJDK JDK for windows nano"
            args:
                - OJDK_URL=https://aka.ms/download-jdk/microsoft-jdk-21.0.2-windows-x64.zip
                - OJDK_SHA256=c910723abc9e2d9ee98c537278076e2b89489449839be2d16715b7dacd378663
                - WINDOWS_TAG=${WINDOWS_TAG}
        image: buildhelpers:jdk-21.0.2-${WINDOWS_TAG:?tag must be given}
        hostname: jdk
        isolation: hyperv

    mvn:
        build:
            context: ./maven
            dockerfile: DockerFile
            labels:
                com.enioka.description: "build helper - Maven build for windows nano"
            args:
                - JAVA_VERSION=21.0.2
                - WINDOWS_TAG=${WINDOWS_TAG}
                - MVN_VERSION=3.9.6
                - MVN_MD5=0eb0432004a91ebf399314ad33e5aaffec3d3b29279f2f143b2f43ade26f4db7bd1c0f08e436e9445ac6dc4a564a2945d13072a160ae54a930e90581284d6461
        image: buildhelpers:maven-3-${WINDOWS_TAG:?tag must be given}
        hostname: maven
        isolation: hyperv

    jqm:
        build:
            context: ../../
            dockerfile: ./docker/windows/jqm/DockerFile
            labels:
                com.enioka.description: "official JQM Docker distribution"
            args:
                - JAVA_VERSION=21.0.2
                - WINDOWS_TAG=${WINDOWS_TAG}
        image: ${JQM_IMAGE_NAME}
        isolation: hyperv
