/**
 * Copyright © 2013 enioka. All rights reserved
 * Authors: Marc-Antoine GOUILLART (marc-antoine.gouillart@enioka.com)
 *          Pierre COPPEE (pierre.coppee@enioka.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.enioka.jqm.jpamodel;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Index;

/**
 * <strong>Not part of any API - this an internal JQM class and may change without notice.</strong> <br>
 * JPA persistence class for storing pointers towards files created by {@link JobInstance}.
 */
@Entity
@Table(name = "Deliverable")
public class Deliverable implements Serializable
{
    private static final long serialVersionUID = 4803101067798401977L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    protected Integer id;

    @Column(length = 1024, name = "filepath")
    protected String filePath;

    @Column(length = 100, name = "file_family")
    protected String fileFamily;

    @Index(name = "fk_jobinstance")
    @Column(nullable = false, name = "jobId")
    private Integer jobId;

    @Column(name = "randomId", length = 200, unique = true)
    private String randomId;

    @Column(name = "originalFileName", length = 1024)
    private String originalFileName;

    /**
     * This is an optional classification tag. Max length is 100.
     */
    public String getFileFamily()
    {
        return fileFamily;
    }

    /**
     * See {@link #getFileFamily()}
     */
    public void setFileFamily(final String fileFamily)
    {
        this.fileFamily = fileFamily;
    }

    /**
     * ID of the {@link JobInstance} which created this {@link Deliverable}. This is also the ID of the {@link History} object once the
     * {@link JobInstance} has finished (and therefore disappeared)
     */
    public Integer getJobId()
    {
        return jobId;
    }

    /**
     * See {@link #getJobId()}
     */
    public void setJobId(final Integer jobId)
    {

        this.jobId = jobId;
    }

    /**
     * Path of the file where it can be retrieved. It is relative to {@link Node#getDlRepo()}
     */
    public String getFilePath()
    {
        return filePath;
    }

    /**
     * See {@link #getFilePath()}
     */
    public void setFilePath(final String filePath)
    {

        this.filePath = filePath;
    }

    /**
     * A technical ID without any meaning. Generated by the database.
     */
    public Integer getId()
    {
        return id;
    }

    /**
     * Should never be called. See {@link #getId()}
     */
    void setId(Integer id)
    {
        this.id = id;
    }

    /**
     * The name of the file that was created by the {@link JobInstance}, before it was renamed to avoid file name collisions. This name is
     * stored as a precaution, but it is better to use {@link #getFileFamily()} to tag files with a meaningful name.
     */
    public String getOriginalFileName()
    {
        return originalFileName;
    }

    /**
     * See {@link #getOriginalFileName()}
     */
    public void setOriginalFileName(String originalFileName)
    {
        this.originalFileName = originalFileName;
    }

    /**
     * Each {@link Deliverable} is associated to a stable random UUID. This UUID can be used to retrieve the file through the servlet API.
     * (this in turn enables some 'security' through obscurity, as file names cannot be guessed easily)
     */
    public String getRandomId()
    {
        return randomId;
    }

    /**
     * See {@link #getRandomId()}
     */
    public void setRandomId(String randomId)
    {
        this.randomId = randomId;
    }
}
