/**
 * Copyright © 2013 enioka. All rights reserved
 * Authors: Marc-Antoine GOUILLART (marc-antoine.gouillart@enioka.com)
 *          Pierre COPPEE (pierre.coppee@enioka.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.enioka.jqm.jpamodel;

import java.io.Serializable;
import java.util.Calendar;

import com.enioka.jqm.jdbc.DbConn;

/**
 * <strong>Not part of any API - this an internal JQM class and may change without notice.</strong> <br>
 * Persistence class for storing the execution requests. Said otherwise, <strong>this table holds the contents of the execution
 * queues</strong>.
 */
public class JobInstance implements Serializable
{
    private static final long serialVersionUID = -7710486847228806301L;

    private Integer id;

    private int jd_id;
    private int queue_id;
    private int node_id;
    private State state;

    private double internalPosition;

    private Integer parentId;
    private String email;
    private Integer progress;

    private Calendar creationDate;
    private Calendar attributionDate;
    private Calendar executionDate;

    private String userName;
    private String sessionID;
    private String instanceApplication;
    private String instanceModule;
    private String instanceKeyword1;
    private String instanceKeyword2;
    private String instanceKeyword3;

    /**
     * The place inside the queue, i.e. the number of job requests that will be run before this one can be run.
     */
    public int getCurrentPosition(DbConn conn)
    {
        if (this.state.equals(State.SUBMITTED))
        {
            return conn.runSelectSingle("ji_select_current_pos", Integer.class, this.internalPosition) + 1;
        }
        else
        {
            return 0;
        }
    }

    /**
     * Helper method to add a parameter without having to create it explicitely. The created parameter should be persisted afterwards.
     * 
     * @param key
     *            name of the parameter to add
     * @param value
     *            value of the parameter to create
     * @return the newly created parameter
     */
    public RuntimeParameter addParameter(String key, String value)
    {
        RuntimeParameter jp = new RuntimeParameter();
        jp.setJi(this.getId());
        jp.setKey(key);
        jp.setValue(value);
        return jp;
    }

    /**
     * A technical ID without any meaning. Generated by the database.
     */
    public int getId()
    {
        return id;
    }

    /**
     * An optional classification tag which can be specified inside the execution request (default is NULL).
     */
    public String getUserName()
    {
        return userName;
    }

    /**
     * An optional classification tag which can be specified inside the execution request (default is NULL).
     */
    public String getSessionID()
    {
        return sessionID;
    }

    /**
     * The {@link JobDef} from which this {@link JobInstance} was instantiated.
     */
    public int getJd()
    {
        return jd_id;
    }

    /**
     * See {@link #getJd()}
     */
    public void setJd(final int jd)
    {
        this.jd_id = jd;
    }

    /**
     * The current status of the request. See {@link State}.
     */
    public State getState()
    {
        return state;
    }

    /**
     * See {@link #getState()}
     */
    public void setState(State state)
    {
        this.state = state;
    }

    /**
     * See {@link #getUserName()}
     */
    public void setUserName(final String user)
    {
        this.userName = user;
    }

    /**
     * See {@link #getSessionID()}
     */
    public void setSessionID(final String sessionID)
    {
        this.sessionID = sessionID;
    }

    /**
     * The {@link Queue} on which is the {@link JobInstance} should wait. Cannot be changed once the status is ATTRIBUTED (i.e. wait is
     * over).
     */
    public int getQueue()
    {
        return queue_id;
    }

    /**
     * See {@link #getQueue()}
     */
    public void setQueue(final int queue)
    {
        this.queue_id = queue;
    }

    /**
     * The node that is running the {@link JobInstance}. Null until wait is over and status is ATTRIBUTED.
     */
    public int getNode()
    {
        return node_id;
    }

    /**
     * See {@link #getNode()}
     */
    public void setNode(final int node)
    {
        this.node_id = node;
    }

    /**
     * Null by default. If specified, an e-mail will be sent to this address at run end.
     */
    public String getEmail()
    {
        return email;
    }

    /**
     * See {@link #getEmail()}
     */
    public void setEmail(String email)
    {
        this.email = email;
    }

    /**
     * User code may signal its progress through this integer. Purely optional.
     */
    public Integer getProgress()
    {
        return progress;
    }

    /**
     * See {@link #getProgress()}
     */
    public void setProgress(Integer progress)
    {
        this.progress = progress;
    }

    /**
     * Technical queue ordering field.
     */
    public double getInternalPosition()
    {
        return internalPosition;
    }

    /**
     * See {@link #getInternalPosition()}
     */
    public void setInternalPosition(double internalPosition)
    {
        this.internalPosition = internalPosition;
    }

    /**
     * Only set when a job request is created by a running job, in which case it contains the job {@link JobInstance} ID.
     */
    public Integer getParentId()
    {
        return parentId;
    }

    /**
     * See {@link #getParentId()}
     */
    public void setParentId(Integer parentId)
    {
        this.parentId = parentId;
    }

    /**
     * Time at which this {@link JobInstance} was committed inside the database.
     */
    public Calendar getCreationDate()
    {
        return creationDate;
    }

    /**
     * See {@link #getCreationDate()}
     */
    public void setCreationDate(Calendar creationDate)
    {
        this.creationDate = creationDate;
    }

    /**
     * An optional classification tag which can be specified inside the execution request (default is NULL).
     */
    public String getApplication()
    {
        return instanceApplication;
    }

    /**
     * See {@link #getApplication()}
     */
    public void setApplication(String application)
    {
        this.instanceApplication = application;
    }

    /**
     * An optional classification tag which can be specified inside the execution request (default is NULL).
     */
    public String getModule()
    {
        return instanceModule;
    }

    /**
     * See {@link #getModule()}
     */
    public void setModule(String module)
    {
        this.instanceModule = module;
    }

    /**
     * An optional classification tag which can be specified inside the execution request (default is NULL).
     */
    public String getKeyword1()
    {
        return instanceKeyword1;
    }

    /**
     * See {@link #getKeyword1()}
     */
    public void setKeyword1(String keyword1)
    {
        this.instanceKeyword1 = keyword1;
    }

    /**
     * An optional classification tag which can be specified inside the execution request (default is NULL).
     */
    public String getKeyword2()
    {
        return instanceKeyword2;
    }

    /**
     * See {@link #getKeyword2()}
     */
    public void setKeyword2(String keyword2)
    {
        this.instanceKeyword2 = keyword2;
    }

    /**
     * An optional classification tag which can be specified inside the execution request (default is NULL).
     */
    public String getKeyword3()
    {
        return instanceKeyword3;
    }

    /**
     * See {@link #getKeyword3()}
     */
    public void setKeyword3(String keyword3)
    {
        this.instanceKeyword3 = keyword3;
    }

    void setId(Integer id)
    {
        this.id = id;
    }

    /**
     * Time at which the execution request entered the RUNNING status - a few milliseconds before actual execution.
     */
    public Calendar getExecutionDate()
    {
        return executionDate;
    }

    /**
     * See {@link #getExecutionDate()}
     */
    public void setExecutionDate(Calendar executionDate)
    {
        this.executionDate = executionDate;
    }

    /**
     * Time at which the job execution request (the {@link JobInstance}) was taken by an engine.
     */
    public Calendar getAttributionDate()
    {
        return attributionDate;
    }

    /**
     * See {@link #getAttributionDate()}
     */
    public void setAttributionDate(Calendar attributionDate)
    {
        this.attributionDate = attributionDate;
    }
}
