ARG WINDOWS_TAG



FROM mcr.microsoft.com/powershell:nanoserver-${WINDOWS_TAG} as installer

SHELL ["pwsh.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

#ENV DOWNLOAD_URL https://download.sonatype.com/nexus/3/latest-win64.zip # redirection issue (HTTPS -> HTTP -> HTTPS...)
ENV DOWNLOAD_URL http://download.sonatype.com/nexus/3/nexus-3.20.1-01-win64.zip

WORKDIR /nexus

RUN invoke-webrequest $env:DOWNLOAD_URL -OutFile nexus.zip -UseBasicParsing -MaximumRedirection 3
RUN Expand-Archive nexus* -DestinationPath .; \
    mkdir -force sonatype-work/nexus3/etc >$null; \
    mkdir -force sonatype-work/nexus3/log >$null; \
    mv nexus* nexus ; \
    echo "nexus-edition=nexus-oss-edition`nnexus-features=nexus-oss-feature" >> C:/nexus/sonatype-work/nexus3/etc/nexus.properties ;

COPY nexus.vmoptions C:/nexus/nexus/bin/



FROM mcr.microsoft.com/windows/nanoserver:${WINDOWS_TAG}

USER ContainerAdministrator
COPY --from=installer C:/nexus/ C:/nexus/

LABEL maintainer="Enioka" \
    readme.md="https://github.com/enioka/jqm/blob/master/README.md" \
    description="Unofficial Sonatype Nexus OSS image for Docker for Windows Nano. (official images are for Linux). Sometimes updated. Build helper for enioka projects - please use official images and not this if you need a Nexus."

VOLUME c:/nexus/sonatype-work/
EXPOSE 8081

ENTRYPOINT C:\nexus\nexus\bin\nexus.exe /run
