'use strict';

var jqmControllers = angular.module('jqmControllers');

jqmControllers.controller('µPrmListCtrl', function($scope, $http, µPrmDto)
{
    $scope.prms = null;
    $scope.selected = [];

    $scope.newprm = function()
    {
        var t = new µPrmDto({
            key : 'name',
            value : 'enter value',
        });
        $scope.prms.push(t);
        $scope.selected.push(t);
    };

    $scope.save = function()
    {
        // Save and refresh the table - ID may have been generated by the server.
        µPrmDto.saveAll({}, $scope.prms, $scope.refresh);
    };

    $scope.refresh = function()
    {
        $scope.selected.length = 0;
        $scope.prms = µPrmDto.query();
    };

    // Only remove from list - save() will sync the list with the server so no need to delete it from server now
    $scope.remove = function()
    {
        var q = null;
        for ( var i = 0; i < $scope.selected.length; i++)
        {
            q = $scope.selected[i];
            $scope.prms.splice($scope.prms.indexOf(q), 1);
        }
        $scope.selected.length = 0;
    };

    $scope.gridOptions = {
        data : 'prms',
        enableCellSelection : true,
        enableRowSelection : true,
        enableCellEditOnFocus : true,
        multiSelect : true,
        showSelectionCheckbox : true,
        selectWithCheckboxOnly : true,
        selectedItems : $scope.selected,

        columnDefs : [ {
            field : 'key',
            displayName : 'Name'
        }, {
            field : 'value',
            displayName : 'Value'
        } ]
    };

    $scope.refresh();
});
