version: "3.7"
services:
    db:
        image: mysql:5.7
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: vip
        environment:
            - MYSQL_ROOT_PASSWORD=superpassword
            - MYSQL_DATABASE=jqm
            - MYSQL_USER=jqm
            - MYSQL_PASSWORD=jqm
        volumes:
            - jqmdbdata:/var/lib/mysql

    jqmbootstrap:
        # Create the database schema on startup and stops.
        build:
            context: .
            args:
                - JQM_VERSION=${JQM_VERSION:-latest}
        image: enioka/jqm:pgsql-${JQM_VERSION:-latest}
        environment:
            - JQM_INIT_MODE=UPDATER
            - JQM_POOL_CONNSTR=jdbc:mysql://db/jqm
            - JQM_POOL_VALIDATION_QUERY=SELECT 1
            - JQM_POOL_DRIVER=com.mysql.jdbc.Driver
            - JQM_POOL_USER=jqm
            - JQM_POOL_PASSWORD=jqm
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: vip
            restart_policy:
                condition: none

    jqmweb:
        build:
            context: .
            args:
                - JQM_VERSION=${JQM_VERSION:-latest}
        image: enioka/jqm:pgsql-${JQM_VERSION:-latest}
        environment:
            - JQM_NODE_NAME=_localhost_
            - JQM_NODE_WS_INTERFACE=_localhost_
            - JQM_INIT_MODE=CLUSTER
            - JQM_CREATE_NODE_TEMPLATE=TEMPLATE_WEB
            - JQM_POOL_CONNSTR=jdbc:mysql://db/jqm
            - JQM_POOL_VALIDATION_QUERY=SELECT 1
            - JQM_POOL_DRIVER=com.mysql.jdbc.Driver
            - JQM_POOL_USER=jqm
            - JQM_POOL_PASSWORD=jqm
        ports:
            - target: 1789
              published: 1789
              protocol: tcp
              mode: ingress
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: vip

    jqmworker:
        build:
            context: .
            args:
                - JQM_VERSION=${JQM_VERSION:-latest}
        image: enioka/jqm:pgsql-${JQM_VERSION:-latest}
        environment:
            - JQM_NODE_NAME=_localhost_
            - JQM_NODE_WS_INTERFACE=_localhost_
            - JQM_INIT_MODE=CLUSTER
            - JQM_CREATE_NODE_TEMPLATE=TEMPLATE_DRONE
            - JQM_POOL_CONNSTR=jdbc:mysql://db/jqm
            - JQM_POOL_VALIDATION_QUERY=SELECT 1
            - JQM_POOL_DRIVER=com.mysql.jdbc.Driver
            - JQM_POOL_USER=jqm
            - JQM_POOL_PASSWORD=jqm
        deploy:
            mode: replicated
            replicas: 2
            endpoint_mode: vip

    adminer:
        image: adminer
        ports:
        - 8080:8080

volumes:
    jqmdbdata:
