###############################################################################
## Build inside full JDK image.
###############################################################################
FROM enioka/buildhelpers:maven-3.5.2 AS builder

ARG MVN_SETTINGS=" "
ARG SKIP_TESTS=true

WORKDIR /jqm-all

# This WILL download the whole Maven Central repository on each build.
# Attempt 1 to avoid this: 
# Copy all poms ls -Recurse pom.xml | resolve-path -Relative |? {select-string -NotMatch "target|bin" -InputObject $_} |% {echo "COPY $_ $(Split-Path -Parent $_)\".Replace("\", "/")}
# RUN mvn dependency:go-offline # sadly no: https://issues.apache.org/jira/browse/MDEP-204 (reactor not used by this goal)

# Attempt 2: use Nexus in another container. But Nexus (like most Java programs) has big issues when using volumes due to a JDK bug...
# If you HAVE a Nexus or another Central caching reverse proxy, just use setting.xml.

# Build
COPY ./docker/windows/nexus/settings.xml ./jqm-all ./

RUN mvn install -DskipTests %MVN_SETTINGS%
RUN IF /I NOT "%SKIP_TESTS%" == "true" (mvn test) ELSE (echo "Skipping tests")



###############################################################################
## Powershell so as to unzip
###############################################################################
FROM microsoft/powershell:nanoserver AS installer

SHELL ["pwsh.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

COPY --from=builder c:/jqm-all/jqm-service/target/jqm-2.1.0-SNAPSHOT.zip .

RUN Expand-Archive jqm*.zip -DestinationPath C:/; \
    rm *.zip; \
	mv jqm* c:/jqm;
#	mkdir c:/jqm/jobs/jqm-demo/jqm-test-pyl/lib/


	
###############################################################################
## Actual image, based on minimal JRE.
###############################################################################
FROM enioka/buildhelpers:jre-1.8.0.151-1

COPY --from=installer C:/jqm/ C:/jqm/
COPY ./docker/windows/jqm/selfConfig.xml C:/jqm/selfConfig.xml

ENV JAVA_OPTS "-Xms128m -Xmx512m -XX:MaxMetaspaceSize=128m"

EXPOSE 1789 1790 1791

# Configuration
WORKDIR C:/jqm
RUN java -jar jqm.jar -u && java -jar jqm.jar -c selfConfig.xml && java -jar jqm.jar -importjobdef ./jobs/jqm-demo/xml/xml-jd-demo.xml && DEL /Q .\\logs\\*

ENTRYPOINT java %JAVA_OPTS% -jar jqm.jar -startnode ContainerNode
