/**
 * Copyright © 2013 enioka. All rights reserved
 * Authors: Marc-Antoine GOUILLART (marc-antoine.gouillart@enioka.com)
 *          Pierre COPPEE (pierre.coppee@enioka.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.enioka.jqm.model;

import java.io.Serializable;
import java.util.Calendar;

import com.enioka.jqm.jdbc.DbConn;
import com.enioka.jqm.jdbc.QueryResult;

/**
 * <strong>Not part of any API - this an internal JQM class and may change without notice.</strong> <br>
 * Persistence class for storing short messages that can be created by user code to inform users or systems of its progress. Often, a
 * {@link Message} is created for each big step inside the user code.<br>
 * This is used both by queued {@link JobInstance}s and archived {@link History} elements.
 */
public class Message implements Serializable
{
    private static final long serialVersionUID = 1234454709423602792L;

    private long id;

    private String textMessage;

    private long ji;

    private Calendar creationDate;

    /**
     * A technical ID without any meaning. Generated by the database.
     *
     * @return long
     */
    public long getId()
    {
        return id;
    }

    /**
     * See {@link #getId()}
     *
     * @param id
     *            id to set
     */
    void setId(final long id)
    {
        this.id = id;
    }

    /**
     * The actual message.<br>
     * Max length is 1000.
     *
     * @return String
     */
    public String getTextMessage()
    {
        return textMessage;
    }

    /**
     * See {@link #getTextMessage()}
     *
     * @param textMessage
     *            message to set
     */
    public void setTextMessage(final String textMessage)
    {
        this.textMessage = textMessage;
    }

    /**
     * The ID of the corresponding JobInstance or History
     *
     * @return long
     */
    public long getJi()
    {
        return ji;
    }

    /**
     * See {@link #getJi()}
     *
     * @param ji
     *            job instance id
     */
    public void setJi(long ji)
    {
        this.ji = ji;
    }

    /**
     * Time at which the message was created, set automatically to current time.
     *
     * @return Calendar
     */
    public Calendar getCreationDate()
    {
        return creationDate;
    }

    /**
     * Create a new entry in the database. No commit performed.
     *
     * @param cnx
     *            db connection
     * @param textMessage
     *            message text
     * @param jobId
     *            job instance id
     * @return long
     */
    public static long create(DbConn cnx, String textMessage, long jobId)
    {
        QueryResult r = cnx.runUpdate("message_insert", jobId, textMessage);

        return r.getGeneratedId();
    }
}
