CREATE MEMORY TABLE __T__INPUT_FILE
(
	ID INTEGER NOT NULL,
	FILE_FAMILY VARCHAR(100),
	PATH VARCHAR(1024),
	JOB_INSTANCE INTEGER NOT NULL, /* Not an FK, as this is used by both History and JobDef */
	ORIGINAL_FILE_NAME VARCHAR(1024),
    STORAGE_NODE INTEGER,

	CONSTRAINT PK_INPUT_FILE PRIMARY KEY(ID)
);
CREATE INDEX IDX_FK_INPUT_FILE_1 ON __T__INPUT_FILE(JOB_INSTANCE);
