/* Data migration script for TIMESTAMP column to DATETIME column */

/* This is very important to ensure the proper conversion from TIMESTAMP to DATETIME in UTC */
SET time_zone = "UTC";

ALTER TABLE __T__VERSION CHANGE INSTALL_DATE INSTALL_DATE DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE __T__NODE CHANGE LAST_SEEN_ALIVE LAST_SEEN_ALIVE DATETIME(3) NULL;

ALTER TABLE __T__QUEUE_NODE_MAPPING CHANGE LAST_MODIFIED LAST_MODIFIED DATETIME(3) NULL;

ALTER TABLE __T__JOB_SCHEDULE CHANGE LAST_UPDATED LAST_UPDATED DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE __T__JOB_INSTANCE CHANGE DATE_ENQUEUE DATE_ENQUEUE DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE __T__JOB_INSTANCE CHANGE DATE_ATTRIBUTION DATE_ATTRIBUTION DATETIME(3) NULL;
ALTER TABLE __T__JOB_INSTANCE CHANGE DATE_START DATE_START DATETIME(3) NULL;
ALTER TABLE __T__JOB_INSTANCE CHANGE DATE_NOT_BEFORE DATE_NOT_BEFORE DATETIME(3) NULL;

ALTER TABLE __T__HISTORY CHANGE DATE_ENQUEUE DATE_ENQUEUE DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE __T__HISTORY CHANGE DATE_ATTRIBUTION DATE_ATTRIBUTION DATETIME(3) NULL;
ALTER TABLE __T__HISTORY CHANGE DATE_START DATE_START DATETIME(3) NULL;
ALTER TABLE __T__HISTORY CHANGE DATE_END DATE_END DATETIME(3) NULL;

ALTER TABLE __T__JNDI_OBJECT_RESOURCE CHANGE LAST_MODIFIED LAST_MODIFIED DATETIME(3) NULL;

ALTER TABLE __T__JNDI_OR_PARAMETER CHANGE LAST_MODIFIED LAST_MODIFIED DATETIME(3) NULL;

ALTER TABLE __T__RUSER CHANGE CREATION_DATE CREATION_DATE DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE __T__RUSER CHANGE EXPIRATION_DATE EXPIRATION_DATE DATETIME(3) NULL;

ALTER TABLE __T__RUSER CHANGE LAST_MODIFIED LAST_MODIFIED DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE __T__GLOBAL_PARAMETER CHANGE LAST_MODIFIED LAST_MODIFIED DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE __T__WITNESS CHANGE LATEST_CONTACT LATEST_CONTACT DATETIME(3) NULL;
