/* This file must be idempotent - it is run on each db upgrade */

CREATE TABLE IF NOT EXISTS __T__JQM_SEQUENCE
(
	name VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY,
	next INTEGER NOT NULL
);

INSERT IGNORE INTO __T__JQM_SEQUENCE(NAME, NEXT) VALUES ('MAIN', 1);

DROP FUNCTION IF EXISTS NEXTVAL;
